
../../bin/lbwbase/RESS.HQR: build/0001-empty.bin build/0002-empty.bin build/0003-empty.bin build/0004-empty.bin build/0005-empty.bin build/0006-empty.bin build/0007-empty.bin build/0008-empty.bin build/0009-empty.bin build/0010-lbwengine.bin
	../../bin/hqrpak -c $@ $^

build/0001-empty.bin:
	cp src/0001-empty.bin $@

build/0002-empty.bin:
	cp src/0002-empty.bin $@

build/0003-empty.bin:
	cp src/0003-empty.bin $@

build/0004-empty.bin:
	cp src/0004-empty.bin $@

build/0005-empty.bin:
	cp src/0005-empty.bin $@

build/0006-empty.bin:
	cp src/0006-empty.bin $@

build/0007-empty.bin:
	cp src/0007-empty.bin $@

build/0008-empty.bin:
	cp src/0008-empty.bin $@

build/0009-empty.bin:
	cp src/0008-empty.bin $@

build/0010-lbwengine.bin: src/0010-lbwengine.png src/lba1-resshqr-0028.gpl
	../../bin/png2rawimage src/0010-lbwengine.png src/lba1-resshqr-0028.gpl build/0010-lbwengine.bin
